version: '3.7'
services:
  vault:
    image: hashicorp/vault
    restart: always
    volumes:
      - "vault-logs:/vault/logs"
      - "vault-data:/vault/file"
      - "./helpers:/helpers"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    container_name: vault
    entrypoint: "vault server -config=/helpers/vault-config.hcl"

volumes:
  vault-logs:
  vault-data:
    external: true
