---
services:
  vault:
    image: hashicorp/vault
    restart: always
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    volumes:
      - "./logs:/vault/logs"
      - "./data:/vault/file"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command:
      - "server"

  vault-init:
    image: hashicorp/vault
    command:
      - "sh"
      - "-c"
      - "/helpers/init.sh"
    environment:
      VAULT_ADDR: "http://vault:8200"
    volumes:
      - "./helpers:/helpers"
      - "./keys:/keys"
    depends_on:
      vault:
        condition: service_started
